#import os
#from os import path

Environment(tools=['install'])
AddOption('--libdir',
      dest='libdir',
      type='string',
      nargs=1,
      action='store',
      default='/usr/lib',
      metavar='DIR',
      help='installation libdir')
AddOption('--libsysdir',
      dest='libsysdir',
      type='string',
      nargs=1,
      action='store',
      default='/lib',
      metavar='DIR',
      help='installation libsysdir')
AddOption('--localstatedir',
      dest='localstatedir',
      type='string',
      nargs=1,
      action='store',
      default='/var/lib',
      metavar='DIR',
      help='installation localstatedir')
env = Environment(LIBDIR = GetOption('libdir'),
                  LIBSYSDIR = GetOption('libsysdir'),
                  LOCALSTATEDIR = GetOption('localstatedir'))
env.Tool('slice2cpp', toolpath=['tools'])

env['CPPPATH'] = ['#.']
env['CPPFLAGS'] = ['-DNSS_TARTARUS_SOCKET_DIR=\\"$LOCALSTATEDIR/tnscd\\"']

destdir = GetOption('install_sandbox')
destdir = destdir if destdir else '/'
env['DESTDIR'] = destdir
Alias('install', destdir)

if 'DEBUG' in ARGUMENTS and ARGUMENTS['DEBUG'] == 'yes':
    env['CPPFLAGS'] = ['-DDEBUG', '-g']
else:
    env['CCFLAGS'] = ['-O2']
Export('env')

rpc = SConscript('RPC/SConscript')
Export('rpc')

SConscript('NSCD/SConscript')
SConscript('nss/SConscript')

Alias('install', FindInstalledFiles())
