opts = Options()
opts.Add('DESTDIR', 'Directory to install', '')
env = Environment(options=opts)
Help(opts.GenerateHelpText(env))

env['BUILDERS']['Ice'] = Builder(action = 'cd `dirname $TARGET`; slice2cpp $SOURCE', src_suffix='.ice', suffix='.cpp')
env['CPPPATH'] = ['#.']

if 'DEBUG' in ARGUMENTS and ARGUMENTS['DEBUG'] == 'yes':
    env['CPPFLAGS'] = ['-DDEBUG', '-g']
else:
    env['CCFLAGS'] = ['-O2']
Export('env')

rpc = SConscript('RPC/SConscript')
Export('rpc')
#env.Install('/usr/lib', [rpc])

tnscd = SConscript('NSCD/SConscript')
env.Install('$DESTDIR/usr/sbin', tnscd)
env.Alias('install', '$DESTDIR/usr/sbin'

nss = SConscript('nss/SConscript')
nss_inst = env.Install('$DESTDIR/lib', nss)
env.Alias('install', env.Command('$DESTDIR/lib/nss_tartarus.so.2', nss_inst, 'ln -s `basename $SOURCE` $TARGET'))
