from glob import glob
from os import path

Import('env')
env = env.Clone()

env.Append(LIBS = ['json_spirit'])
rpc = env.SharedLibrary('tartarus-rpc', ['server.cpp', 'boost_error_code.cpp'])

Return('rpc')
