from glob import glob
from os import path

Import('env', 'json')
env = env.Clone()

env['LIBS'] = path.basename(str(json[0]))[:-3]
env['LIBPATH'] = path.dirname(str(json[0]))
rpc = env.SharedLibrary('tartarus-rpc', glob('*.cpp'))

Return('rpc')
