from glob import glob
from os import path

Import('env')
env = env.Clone()

NAME = "libnss_tartarus"
SUFFIX = ".so.2"
SONAME = NAME + SUFFIX
env["SHLIBSUFFIX"] = [SUFFIX + '.0.0']
env["LINKFLAGS"] = ['-Wl,-soname,' + SONAME]
env["CPPFLAGS"] = '-DBOOST_DISABLE_THREADS'

env.Append(LIBS=['json_spirit'])

nss = env.SharedLibrary('nss_tartarus', glob('*.cpp') + ['#RPC/client.cpp'])

Command('libnss_tartarus.so', nss, 'ln -fs `basename $SOURCE` $TARGET')
Program('test.c', LIBPATH='.', LIBS='nss_tartarus')

Return('nss')
