from glob import glob
from os.path import join
from os import path

Import('env')
env = env.Clone()

NAME = "libnss_tartarus"
SUFFIX = ".so.2"
SONAME = NAME + SUFFIX
DEVNAME = NAME + ".so"
env["SHLIBSUFFIX"] = [SUFFIX + '.0.0']
env["LINKFLAGS"] = ['-Wl,-soname,' + SONAME]
env.Append(CPPFLAGS = '-DBOOST_DISABLE_THREADS')
env.Append(LIBS=['json_spirit', 'boost_system'])

nss = env.SharedLibrary('nss_tartarus', glob('*.cpp') + ['#RPC/client.cpp'])
inst_nss = env.Install('$LIBSYSDIR', nss)
env.Command(join('$DESTDIR', '$LIBSYSDIR', SONAME), inst_nss, 'ln -fs `basename $SOURCE` $TARGET')

Command(DEVNAME, nss, 'ln -fs `basename $SOURCE` $TARGET')
Program('test.c', LIBPATH='.', LIBS='nss_tartarus')

Return('nss')
