from os import path
from subprocess import Popen, PIPE

Import('env', 'rpc')

env = env.Clone()
env.Append(LIBS=['Ice'])
env.ParseConfig("pkg-config krb5user --cflags --libs")
env['CPPPATH'] += ['.']

libs = [path.basename(str(i[0])) for i in (rpc,)]
libpath = [path.dirname(str(i[0])) for i in (rpc,)]

env.Append(LIBS=libs + ['json_spirit', 'boost_system'])
env['LIBPATH'] = libpath

env.Append(ICE2CPP_INCPATH=['/usr/share/Tartarus/slice'])
core, _ = env.Slice2Cpp('/usr/share/Tartarus/slice/core/exceptions.ice', ICE2CPP_OUTDIR="core", ICE2CPP_FLAGS='--include-dir=core')
sysdb, _ = env.Slice2Cpp('/usr/share/Tartarus/slice/SysDB/SysDB.ice', ICE2CPP_OUTDIR="SysDB", ICE2CPP_FLAGS='--include-dir=SysDB')

src = Glob('*.cpp')
tnscd = env.Program('tnscd', src + [core, sysdb])
Install('/usr/sbin', tnscd)

Return('tnscd')
