if(NOT DEFINED DATADIR)
   set(DATADIR share)
endif(NOT DEFINED DATADIR)

if(NOT DEFINED BINDIR)
   set(BINDIR bin)
endif(NOT DEFINED BINDIR)

if(NOT DEFINED SBINDIR)
   set(SBINDIR sbin)
endif(NOT DEFINED SBINDIR)

if(NOT DEFINED LIBDIR)
   set(LIBDIR lib${LIB_SUFFIX})
endif(NOT DEFINED LIBDIR)

if(NOT DEFINED SLIBDIR)
   set(SLIBDIR /lib${LIB_SUFFIX})
endif(NOT DEFINED SLIBDIR)

if(NOT DEFINED DATADIR)
   set(DATADIR share)
endif(NOT DEFINED DATADIR)

if(NOT DEFINED SYSCONFDIR)
    set(SYSCONFDIR /etc)
endif(NOT DEFINED SYSCONFDIR)

if(NOT DEFINED DBUS_SERVICES_DIR)
    set(DBUS_SERVICES_DIR ${DATADIR}/dbus-1/system-services)
endif(NOT DEFINED DBUS_SERVICES_DIR)

if(NOT DEFINED DBUS_CONFIG_DIR)
    set(DBUS_CONFIG_DIR ${SYSCONFDIR}/dbus-1/system.d)
endif(NOT DEFINED DBUS_CONFIG_DIR)

if(NOT DEFINED TARTARUS_CONFIG_DIR)
    set(TARTARUS_CONFIG_DIR ${SYSCONFDIR}/Tartarus/clients)
endif(NOT DEFINED TARTARUS_CONFIG_DIR)
